### ISSUE TITLE
Unable to add class on input

### ISSUE THREAD

**Issue by stefandudasko** [tecbeast42/autocomplete-vue#11]
I am trying to add a class on input so I did as you wrote in docs but the class I am trying to apply is always being applied on the parent div.

```
<autocomplete-vue
       id="getProducts"
       placeholder="Autocomplete"
       :list="{{ $productList }}"
       requestType="get"
       :property="'title'"
       :inputClass="'form-control'"
></autocomplete-vue>
```

**Comment by Humni** [comment]
I solved this by using the following

`input-class="form-control"`
