### ISSUE TITLE
can't set a value into autocomplete-vue and after select the droplist's value, the droplist don't hide

### ISSUE THREAD

**Issue by martinko2009** [tecbeast42/autocomplete-vue#3]
**1、I can't set a value into autocomplete-vue for initial.**
```
import AutocompleteVue from 'autocomplete-vue';
Vue.use(require('vue-resource'));
new Vue({
		el:"#demo",
		data:{
			num:'1'
		},
		components:{
			AutocompleteVue
		}
})
```
html
```
<autocomplete-vue :value="num"></autocomplete-vue>
```
the variable num's value doesn't display in the autocomplete-vue.

**2、After I select one item from the droplist, and droplist doesn't hide self automaticly**

can you tell me how to resolve it.Thank you.

**Comment by tecbeast42** [comment]
1. Can you show more of your code? 
This works just fine.
```
new Vue({
    template: '<autocomplete-vue :value="num"></autocomplete-vue>',
    el: '#app',
    data: {
        num: '1',
    }
});
```
2. Yes this should be added to the next release. Currently this does not work.

**Comment by tecbeast42** [comment]
We have an option now to hide the autocomplete list on select.
