### ISSUE TITLE
inputClass is not working

### ISSUE THREAD

**Issue by michielgerritsen** [tecbeast42/autocomplete-vue#6]
I am pretty new to Vue JS so i may be doing this wrong, but it looks like that the ``inputClass`` option is nog working. My code is looking like this:

```
<autocomplete-vue
        inputClass="form-control"
        :list="[{name: 'item1'}, {name: 'item2'}, {name: 'item3'}]"
        placeholder="Autocomplete"
></autocomplete-vue>
```

But this does not set the class on the input element:
![image](https://user-images.githubusercontent.com/5858697/27432557-ffd3ecae-5750-11e7-961d-69f3722078e9.png)

**Comment by RobinScout** [comment]
You have to write it as input-class (kebab-case) if it is not in a vue-component.
