### ISSUE TITLE
How to set the input name

### ISSUE THREAD

**Issue by dmhamilt** [tecbeast42/autocomplete-vue#7]
I have the demo working but i can't set the input name through the vue component.
`<input type="text" placeholder="name" >` is what the browser returns.

**Comment by tecbeast42** [comment]
What is your original vue code ?

**Comment by dmhamilt** [comment]
this is blade view file. 

`
@extends('layouts.app')

@section('content')

		<div class="container">
		BOO
        <autocomplete-vue property="name" :list="[{name: 'test'}, {name: 'test1'}, {name: 'test123'}, {name: 'test2'}, {name: 'test23'}, {name: 'Test'}]" placeholder="name" :auto-hide="true"></autocomplete-vue>
		</div>


@endsection
`

**Comment by tecbeast42** [comment]
Works as expected. The property attribute just limits the search results to list.<property>.
