### ISSUE TITLE
How to reset autocomplete styles?

### ISSUE THREAD

**Issue by realtebo** [tecbeast42/autocomplete-vue#8]
I'm using this .sass to customize my autocomplete 
```

.autocomplete__suggestions {
    display: flex;
    flex-direction: column;
    flex: 1 0 100%;
    width: auto;
    min-width: 100%;
    font-variant: initial !important;
    .autocomplete__entry {
      font-variant: initial !important;
      font-size: 0.5em !important;
    }
  }

```
My problem is that I got the suggestion in all upper cases, and definitively i don't want this.

PS: thanks for this component !

**Comment by tecbeast42** [comment]
We dont set the suggestions to uppercase. Can you check if you have some CSS rule that sets it to uppercase.
