### ISSUE TITLE
Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by silkyland** [tecbeast42/autocomplete-vue#9]
<img width="486" alt="screen shot 2017-09-12 at 11 43 55 am" src="https://user-images.githubusercontent.com/11696008/30308456-cf24e8de-97af-11e7-8647-55cf5cd0e03b.png">

Error when loading data from server with URL

**Comment by tecbeast42** [comment]
autocomplete-vue expects you to have axios oder vue-resource installed and $http available in your Vue Components. We will add the peerDependencies and add it to the docs

**Comment by tecbeast42** [comment]
#10

**Comment by tecbeast42** [comment]
Please let us know if you still have troulbe after adding axios or vue-resource.
